version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: store
    ports:
      - 5432:5432


  store:
    build:
      context: .
    restart: always
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db/store
      DB_USER: postgres
      DB_PASSWORD: example
    ports:
      - 8080:8080